# Define the New Relic pre-built image
FROM public.ecr.aws/newrelic-lambda-layers-for-docker/newrelic-lambda-layers-nodejs:22 AS layer

# Define the base image
FROM public.ecr.aws/lambda/nodejs:22

# Copy New Relic Layer code
COPY --from=layer /opt/ /opt/

RUN microdnf install -y unzip && microdnf clean all

# Copy across the Serverless zipped artifact
COPY .serverless/api.zip ${LAMBDA_TASK_ROOT}

# Unzip it during build time
RUN unzip api.zip -d . && rm api.zip

# CMD override to New Relic's handler wrapper
CMD [ "newrelic-lambda-wrapper.handler" ]